[project]
name = "aws-lambda-calculator-cli"
dynamic = [ "version" ]
description = ""
authors = [
    {name = "Lior Dux", email = "lior.dux@develeap.com"}
]
maintainers = [
    { name = "Alex Machulsky", email = "alexm051197@gmail.org" },
]
readme = "README.md"
requires-python = ">=3.13"
license = { file = "LICENSE" }

[tool.poetry]
package-mode = false
version = "1.0"  # base version

[tool.poetry.requires-plugins]
poetry-plugin-export = ">=1.8"

# [tool.poetry.dependencies]
# aws-lambda-calculator = {git = "https://github.com/zMynx/aws-lambda-calculator.git", rev = "feat/package", subdirectory = "aws-lambda-calculator"}

[project.urls]
homepage = "https://github.com/zMynx/aws-lambda-calculator"
repository = "https://github.com/zMynx/aws-lambda-calculator"
documentation = "https://github.com/zMynx/aws-lambda-calculator/docs/"

[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
ruff = "^0.9.7"
pytest = "^8.3.4"
mypy = "^1.15.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
