name: Pull Request Labeler
on: pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
      with:
        repo-token: ${{ github.token }} 
        configuration-path: .github/auto-labeler-conf.yaml
        sync-labels: false
        dot: true
