# .github/workflows/ci.yaml
---
name: CI
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  code-checks:
    name: Code Standard Checks 
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: bash
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install poetry 
        run: pipx install poetry==2.1.1

      - name: Setup Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version-file: pyproject.toml
          cache: poetry

      - name: Setup poetry 
        run: |
          python --version
          python -m pip install --upgrade pip
          python -m pip install poetry==2.1.1

      - name: Install dependencies
        run: python -m poetry install

      - name: Lint (ruff)
        run: python -m poetry run ruff format

      - name: Format (black)
        run: python -m poetry run black .

      - name: Types cheking (mypy)
        run: python -m poetry run mypy .

      - name: Commit and push any changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add . && git commit -m "ci: auto-lint updates" --no-verify && git push || echo "No changes to commit"
