# .github/worklows/devpod-amd64.yaml
---
name: Devcontainer Build (amd64)

on:
  workflow_dispatch:
  push:
    paths:
      - '.devcontainer/**'
      - '.github/workflows/devpod-amd64.yaml'

jobs:
  build:
    runs-on:
      - runs-on=${{ github.run_id }}
      - runner=2cpu-linux-x64
      - env=poc
      - spot=lowest-price
      - region=eu-central-1
    permissions:
      contents: read
      packages: write
      id-token: write
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: zmynxx
          password: ${{ secrets.PAT }}

      - id: docker_meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: ghcr.io/zmynx/devpod-demo
          tags: type=sha,format=long

      - name: Install Devpod
        run: |
          curl -L -o devpod "https://github.com/loft-sh/devpod/releases/latest/download/devpod-linux-amd64" && sudo install -c -m 0755 devpod /usr/local/bin && rm -f devpod

      - name: Set Devpod Context Options
        run: devpod context set-options -o REGISTRY_CACHE='ghcr.io/zmynx/devpod-demo'

      - name: Add docker provider
        run: devpod provider add docker || true

      - name: Build with Devpod
        run: |
          #!/bin/bash
          set -exuo pipefail
          devpod build . \
            --repository ghcr.io/zmynx/devpod-demo \
            --provider docker \
            --platform linux/amd64 \
            --tag amd64

      - name: Build with Devpod (windows)
        run: |
          #!/bin/bash
          set -exuo pipefail
          devpod build . \
            --repository ghcr.io/zmynx/devpod-demo \
            --provider docker \
            --platform windows/amd64 \
            --tag amd64
