# .github/workflows/semantic-check.yaml
---
name: Semantic Check

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Semantic Commit Message Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017 # v5.5.3
        name: Check PR for Semantic Commit Message
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          requireScope: false
          validateSingleCommit: true
          ignoreLabels: release merge
