# .github/workflows/semantic-check.yaml
---
name: Semantic Check

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Semantic Commit Message Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5.0.0
        with:
          persist-credentials: false

      - uses: amannn/action-semantic-pull-request@e7d011b07ef37e089bea6539210f6a0d360d8af9 # v6.1.1
        name: Check PR for Semantic Commit Message
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          requireScope: false
          validateSingleCommit: true
          ignoreLabels: release merge
