# .github/workflows/semantic-check.yaml
---
name: Semantic Check

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Semantic Commit Message Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        name: Check PR for Semantic Commit Message
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          requireScope: false
          validateSingleCommit: true
          ignoreLabels: release merge
