# .github/workflows/superlinter.yaml
---
name: SuperLinter
on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  super-linter:
    name: SuperLinter
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: super-linter/super-linter@v7.3.0
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_PYTHON: true
          VALIDATE_YAML: true
          GITHUB_TOKEN: ${{ github.token }}
#          LINTER_RULES_PATH: .github/linters/
          DEFAULT_BRANCH: main

      - name: Check GitHub Actions YAML with actionlint
        uses: reviewdog/action-actionlint@v1