# .github/workflows/ci.yaml
---
name: CI
on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  super-linter:
    name: Lint YAML + Code with Super-Linter
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_PYTHON: true
          VALIDATE_YAML: true
          LINTER_RULES_PATH: .github/linters/
          DEFAULT_BRANCH: main

      - name: Check GitHub Actions YAML with actionlint
        uses: reviewdog/action-actionlint@v1
