# .github/workflows/ci.yaml
---
name: CI
on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  super-linter:
    name: Lint YAML + Code with Super-Linter
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Run Super-Linter
        uses: github/super-linter@b807e99ddd37e444d189cfd2c2ca1274d8ae8ef1 # v7
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_PYTHON: true
          VALIDATE_YAML: true
          LINTER_RULES_PATH: .github/linters/
          DEFAULT_BRANCH: main

      - name: Check GitHub Actions YAML with actionlint
        uses: reviewdog/action-actionlint@93dc1f9bc10856298b6cc1a3b3239cfbbb87fe4b # v1.67.0
