name: Trivy
on:
  push:
    branches: [main]
jobs:
  scan-latest-image:
    name: Scan latest image
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: write
      packages: read
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: ghcr.io/${{ github.repository }}:latest
          format: sarif
          output: trivy-latest-image-results.sarif
        env:
          TRIVY_USERNAME: ${{ github.actor }}
          TRIVY_PASSWORD: ${{ github.token }}
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: trivy-latest-image-results.sarif
  scan-repo:
    name: Scan Repository
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: write
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.30.0
        with:
          scan-type: fs
          ignore-unfixed: true
          format: sarif
          output: trivy-repo-results.sarif
          severity: CRITICAL
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-repo-results.sarif
  generate-sbom:
    name: Generate SBOM
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: write
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Run Trivy in GitHub SBOM mode and submit results to Dependency Graph
        uses: aquasecurity/trivy-action@0.30.0
        with:
          scan-type: fs
          format: github
          output: dependency-results.sbom.json
          image-ref: .
          github-pat: ${{ github.token }}
