import pytest
from aws_lambda_calculator.calculator import calculate


@pytest.mark.parametrize(
    (
        "region",
        "architecture",
        "number_of_requests",
        "request_unit",
        "duration_of_each_request_in_ms",
        "memory",
        "memory_unit",
        "ephemeral_storage",
        "storage_unit",
        "duration_ms",
        "expected_cost",
    ),
    [
        # Free-tier test
        ("us-east-1", "x86", 1_000_000, "per day", 100, 1024, "MB", 128, "MB", 1, 0.0),
        ("us-east-1", "x86", 500_000, "per month", 200, 2048, "MB", 128, "MB", 1, 0.0),
        (
            "us-east-1",
            "x86",
            2_000_000,
            "per day",
            500,
            1536,
            "MB",
            128,
            "MB",
            1,
            18.53337,
        ),
        (
            "us-east-1",
            "x86",
            50_000_000,
            "per day",
            1000,
            2048,
            "MB",
            128,
            "MB",
            1,
            1669.80332,
        ),
        ("us-east-1", "x86", 10_000_000, "per day", 0, 1024, "MB", 128, "MB", 1, 1.8),
        ("us-east-1", "x86", 0, "per day", 100, 1024, "MB", 128, "MB", 1, 0.0),
        (
            "us-east-1",
            "x86",
            1_000_000,
            "per day",
            100,
            8192,
            "MB",
            128,
            "MB",
            1,
            6.66668,
        ),
        (
            "us-east-1",
            "x86",
            5_000_000,
            "per day",
            300,
            2048,
            "MB",
            128,
            "MB",
            1,
            44.13342,
        ),
    ],
)
def test_calculate(
    region,
    architecture,
    number_of_requests,
    request_unit,
    duration_of_each_request_in_ms,
    memory,
    memory_unit,
    ephemeral_storage,
    storage_unit,
    duration_ms,
    expected_cost,
):
    cost = calculate(
        region=region,
        architecture=architecture,
        number_of_requests=number_of_requests,
        request_unit=request_unit,
        duration_of_each_request_in_ms=duration_of_each_request_in_ms,
        memory=memory,
        memory_unit=memory_unit,
        ephemeral_storage=ephemeral_storage,
        storage_unit=storage_unit,
        duration_ms=duration_ms,
    )
    assert round(cost, 5) == round(expected_cost, 5), (
        f"Expected {expected_cost}, got {cost}"
    )
